build: false

environment:
    PYTHON: "C:\\Python36-x64"
    PYTHON_VERSION: "3.6.3"
    PYTHON_ARCH: "64"

    CONAN_UPLOAD: "https://conan.campar.in.tum.de/api/conan/conan-camposs"
    CONAN_REMOTES: "https://conan.campar.in.tum.de/api/conan/conan-camposs, https://api.bintray.com/conan/bincrafters/public-conan"
    CONAN_REFERENCE: "simple/0.9"
    CONAN_USERNAME: "camposs"
    CONAN_CHANNEL: "stable"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools --upgrade
  - conan user # It creates the conan data directory

test_script:
  - python build.py
