/**
 * S.I.M.P.L.E. - Smart Intuitive Messaging Platform with Less Effort
 * Copyright (C) 2018 Salvatore Virga - salvo.virga@tum.de, Fernanda Levy
 * Langsch - fernanda.langsch@tum.de
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#ifndef SIMPLE_MSGS_FLOAT_H
#define SIMPLE_MSGS_FLOAT_H

#include "numeric_type.hpp"

// Specialized functions for NumericType<float>.

namespace simple_msgs {

//! Typedef for Float messages.
using Float = NumericType<float>;

/**
 * @brief Construct a Float message using a raw memory coming from network.
 */
template <>
NumericType<float>::NumericType(const void* data);

/**
 * @brief Copy assignment operator that uses raw memory coming from the network.
 */
template <>
NumericType<float>& NumericType<float>::operator=(std::shared_ptr<void*> rhs);

/**
 * @brief Builds and returns the buffer accordingly to the value currently stored.
 */
template <>
std::shared_ptr<flatbuffers::DetachedBuffer> NumericType<float>::getBufferData() const;

/**
 * @brief Returns an identifier of the message type generated by the flatbuffers.
 */
template <>
std::string NumericType<float>::getTopic();

}  // Namespace simple_msgs.

#endif  // SIMPLE_MSGS_FLOAT_H
